export type OpeningKind = "room_available" | "flatmate_needed" | "full_flat";
export type Furnishing = "furnished" | "semi_furnished" | "unfurnished";
export type OpeningPreference =
  | "anyone"
  | "women_only"
  | "men_only"
  | "family"
  | "working_professionals";
export type OpeningIncluded =
  | "wifi"
  | "ac"
  | "parking"
  | "power_backup"
  | "maid"
  | "cook"
  | "washing_machine";
export type OpeningContactMethod = "whatsapp" | "call";
export type OpeningState = "active" | "filled" | "expired";
export type OpeningBudget = "under_20k" | "from_20k_to_40k" | "over_40k";
export type OpeningSort = "newest" | "rent_asc";

/** A directory card. Only the tower and floor are ever sent, never a unit number. */
export interface FlatOpeningCard {
  id: string;
  kind: OpeningKind;
  /** Generated by the API, e.g. "Room in 1 BHK · Tower C". */
  title: string;
  rentInr: number;
  /** 1 to 4, where 4 means "4+". */
  bhk: number;
  tower: string;
  /** 0 is the ground floor. */
  floor: number | null;
  furnishing: Furnishing;
  /** ISO date; null means "Available now". */
  availableFrom: string | null;
  preference: OpeningPreference;
  description: string;
  contactMethod: OpeningContactMethod;
  postedBy: string;
  postedAt: string;
  isMine: boolean;
  state: OpeningState;
}

export interface FlatOpeningDetail extends FlatOpeningCard {
  towerId: string;
  depositInr: number | null;
  maintenanceIncluded: boolean;
  maintenanceInr: number | null;
  included: OpeningIncluded[];
  poster: { firstName: string; tower: string };
  canRemove: boolean;
  /** Poster only. */
  expiresAt: string | null;
  canRenew: boolean;
}

export interface OpeningOptions {
  firstName: string;
  towerId: string | null;
  towers: { id: string; name: string }[];
  hasPhone: boolean;
}
