import { amenityImageUrl } from "@/lib/amenities/image-url";
import type { AmenityDetail } from "@/lib/types/amenities";

/** Bundled demo amenities when the FastAPI backend is not the data source. */
export const STATIC_AMENITY_DETAILS: AmenityDetail[] = [
  {
    id: "am-gym",
    name: "Gym",
    emoji: "gym",
    status: "moderate",
    detail: "Free till 7pm",
    kind: "walk_in",
    category: "fitness",
    imageUrl: amenityImageUrl("Gym"),
    statusLabel: "Moderate",
    action: "view",
    actionLabel: "View",
    capacity: 30,
    hoursLabel: "6 AM – 10 PM daily",
    rules: [
      "Wipe equipment after use.",
      "Footwear and a towel are required.",
      "Re-rack your weights.",
    ],
    advanceDays: 0,
    maxHoursPerDay: 0,
    canManage: false,
  },
  {
    id: "am-pool",
    name: "Pool",
    emoji: "pool",
    status: "quiet",
    detail: "Free till 8pm",
    kind: "walk_in",
    category: "fitness",
    imageUrl: amenityImageUrl("Pool"),
    statusLabel: "Quiet",
    action: "view",
    actionLabel: "View",
    capacity: 20,
    hoursLabel: "6 AM – 9 PM daily",
    rules: [
      "Shower before you swim.",
      "Swim caps are required.",
      "Children under 12 need an adult.",
    ],
    advanceDays: 0,
    maxHoursPerDay: 0,
    canManage: false,
  },
  {
    id: "am-badminton",
    name: "Badminton 1",
    emoji: "court",
    status: "booked",
    detail: "Busy till 7pm",
    kind: "bookable",
    category: "sports",
    imageUrl: amenityImageUrl("Badminton 1"),
    statusLabel: "Busy",
    action: "book",
    actionLabel: "Book",
    capacity: 4,
    hoursLabel: "6 AM – 10 PM daily",
    rules: [
      "Book up to 7 days ahead, 2 hours a day at most.",
      "Non-marking shoes only.",
      "Cancel early if your plans change.",
    ],
    advanceDays: 7,
    maxHoursPerDay: 2,
    canManage: false,
  },
  {
    id: "am-tennis",
    name: "Tennis Court",
    emoji: "court",
    status: "free",
    detail: "Free till 7pm",
    kind: "bookable",
    category: "sports",
    imageUrl: amenityImageUrl("Tennis Court"),
    statusLabel: "Quiet",
    action: "book",
    actionLabel: "Book",
    capacity: 4,
    hoursLabel: "6 AM – 10 PM daily",
    rules: [
      "Book up to 7 days ahead, 2 hours a day at most.",
      "Non-marking shoes only.",
      "Cancel early if your plans change.",
    ],
    advanceDays: 7,
    maxHoursPerDay: 2,
    canManage: false,
  },
  {
    id: "am-cafe",
    name: "Cafe Lounge",
    emoji: "cafe",
    status: "open",
    detail: "Open now",
    kind: "walk_in",
    category: "other",
    imageUrl: amenityImageUrl("Cafe Lounge"),
    statusLabel: "Quiet",
    action: "view",
    actionLabel: "View",
    capacity: 40,
    hoursLabel: "8 AM – 10 PM daily",
    rules: ["Keep noise low.", "Clear your table when you leave.", "Take your trash with you."],
    advanceDays: 0,
    maxHoursPerDay: 0,
    canManage: false,
  },
];
