"""identity tables

Revision ID: 4025af72491b
Revises: 
Create Date: 2026-09-30 16:43:14.086781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4025af72491b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='society_plan'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_societies'))
    )
    op.create_index(op.f('ix_societies_invite_code'), 'societies', ['invite_code'], unique=True)
    op.create_table('users',
    sa.Column('supabase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String(length=100)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('show_flat', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_profiles_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_society_id'), 'profiles', ['society_id'], unique=False)
    op.create_table('towers',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_towers_society_id_societies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_towers')),
    sa.UniqueConstraint('society_id', 'name', name='uq_towers_society_id_name')
    )
    op.create_index(op.f('ix_towers_society_id'), 'towers', ['society_id'], unique=False)
    op.create_table('flats',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('tower_id', sa.Uuid(), nullable=False),
    sa.Column('flat_no', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_flats_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], name=op.f('fk_flats_tower_id_towers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flats')),
    sa.UniqueConstraint('tower_id', 'flat_no', name='uq_flats_tower_id_flat_no')
    )
    op.create_index(op.f('ix_flats_society_id'), 'flats', ['society_id'], unique=False)
    op.create_index(op.f('ix_flats_tower_id'), 'flats', ['tower_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('flat_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'tenant', 'landlord', 'committee', 'admin', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='membership_status'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], name=op.f('fk_memberships_flat_id_flats'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_memberships_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'society_id', name='uq_memberships_user_id_society_id')
    )
    op.create_index(op.f('ix_memberships_society_id'), 'memberships', ['society_id'], unique=False)
    op.create_index('ix_memberships_society_id_status', 'memberships', ['society_id', 'status'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index('ix_memberships_society_id_status', table_name='memberships')
    op.drop_index(op.f('ix_memberships_society_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_flats_tower_id'), table_name='flats')
    op.drop_index(op.f('ix_flats_society_id'), table_name='flats')
    op.drop_table('flats')
    op.drop_index(op.f('ix_towers_society_id'), table_name='towers')
    op.drop_table('towers')
    op.drop_index(op.f('ix_profiles_society_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_societies_invite_code'), table_name='societies')
    op.drop_table('societies')
    sa.Enum(name="membership_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="membership_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="society_plan").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
