"""amenities community events

Revision ID: eae80a5f26f4
Revises: 4025af72491b
Create Date: 2026-10-01 19:27:23.122968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae80a5f26f4'
down_revision: Union[str, Sequence[str], None] = '4025af72491b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amenity_type', sa.Enum('gym', 'pool', 'court', 'hall', 'amphitheatre', 'other', name='amenity_type'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('open_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_amenities_society_id_societies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenities'))
    )
    op.create_index(op.f('ix_amenities_society_id'), 'amenities', ['society_id'], unique=False)
    op.create_table('groups',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=2048), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_groups_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_groups_society_id_societies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_society_id'), 'groups', ['society_id'], unique=False)
    op.create_table('join_requests',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('group', 'whatsapp', name='join_target_type'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='join_request_status'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_join_requests_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_join_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join_requests'))
    )
    op.create_index(op.f('ix_join_requests_society_id'), 'join_requests', ['society_id'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)
    op.create_table('whatsapp_groups',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('invite_link', sa.String(length=512), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_whatsapp_groups_admin_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_whatsapp_groups_society_id_societies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_groups'))
    )
    op.create_index(op.f('ix_whatsapp_groups_society_id'), 'whatsapp_groups', ['society_id'], unique=False)
    op.create_table('amenity_bookings',
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('time_range', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'pending', 'cancelled', name='amenity_booking_status'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_amenity_bookings_amenity_id_amenities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_amenity_bookings_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_amenity_bookings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenity_bookings'))
    )
    op.create_index(op.f('ix_amenity_bookings_amenity_id'), 'amenity_bookings', ['amenity_id'], unique=False)
    op.create_index(op.f('ix_amenity_bookings_society_id'), 'amenity_bookings', ['society_id'], unique=False)
    op.create_index(op.f('ix_amenity_bookings_user_id'), 'amenity_bookings', ['user_id'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE amenity_bookings ADD CONSTRAINT excl_amenity_bookings_no_overlap
        EXCLUDE USING gist (amenity_id WITH =, time_range WITH &&)
        WHERE (status = 'confirmed')
        """
    )
    op.create_table('amenity_status',
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('crowd_level', sa.Enum('quiet', 'moderate', 'busy', 'closed', name='crowd_level'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_amenity_status_amenity_id_amenities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_amenity_status_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_amenity_status_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('amenity_id', name=op.f('pk_amenity_status'))
    )
    op.create_index(op.f('ix_amenity_status_society_id'), 'amenity_status', ['society_id'], unique=False)
    op.create_table('events',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('public_slug', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.Enum('free', 'paid', 'society', name='event_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=2048), nullable=True),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_id', sa.Uuid(), nullable=True),
    sa.Column('location_label', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'published', 'cancelled', 'completed', name='event_status'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_events_amenity_id_amenities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_events_host_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_events_society_id_societies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('society_id', 'public_slug', name='uq_events_society_id_public_slug')
    )
    op.create_index(op.f('ix_events_host_id'), 'events', ['host_id'], unique=False)
    op.create_index(op.f('ix_events_society_id'), 'events', ['society_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='group_member_role'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_members_group_user')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.ARRAY(sa.String(length=2048)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_posts_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_posts_society_id_societies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_group_id'), 'posts', ['group_id'], unique=False)
    op.create_index(op.f('ix_posts_society_id'), 'posts', ['society_id'], unique=False)
    op.create_table('comments',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('event_tickets',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('reserved', 'confirmed', 'cancelled', name='event_ticket_status'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_tickets_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_event_tickets_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_tickets'))
    )
    op.create_index(op.f('ix_event_tickets_event_id'), 'event_tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_tickets_society_id'), 'event_tickets', ['society_id'], unique=False)
    op.create_index(op.f('ix_event_tickets_user_id'), 'event_tickets', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reaction_type', sa.Enum('like', 'celebrate', 'support', name='reaction_type'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_reactions_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions')),
    sa.UniqueConstraint('post_id', 'user_id', 'reaction_type', name='uq_reactions_post_user_type')
    )
    op.create_index(op.f('ix_reactions_post_id'), 'reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    op.create_table('stall_applications',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('society_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stall_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fee_paise', sa.Integer(), nullable=False),
    sa.Column('spot_no', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paid', name='stall_application_status'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_stall_applications_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_stall_applications_society_id_societies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stall_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stall_applications'))
    )
    op.create_index(op.f('ix_stall_applications_event_id'), 'stall_applications', ['event_id'], unique=False)
    op.create_index(op.f('ix_stall_applications_society_id'), 'stall_applications', ['society_id'], unique=False)
    op.create_index(op.f('ix_stall_applications_user_id'), 'stall_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stall_applications_user_id'), table_name='stall_applications')
    op.drop_index(op.f('ix_stall_applications_society_id'), table_name='stall_applications')
    op.drop_index(op.f('ix_stall_applications_event_id'), table_name='stall_applications')
    op.drop_table('stall_applications')
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_post_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_event_tickets_user_id'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_society_id'), table_name='event_tickets')
    op.drop_index(op.f('ix_event_tickets_event_id'), table_name='event_tickets')
    op.drop_table('event_tickets')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_society_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_group_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_events_society_id'), table_name='events')
    op.drop_index(op.f('ix_events_host_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_amenity_status_society_id'), table_name='amenity_status')
    op.drop_table('amenity_status')
    op.execute(
        "ALTER TABLE amenity_bookings DROP CONSTRAINT IF EXISTS excl_amenity_bookings_no_overlap"
    )
    op.drop_index(op.f('ix_amenity_bookings_user_id'), table_name='amenity_bookings')
    op.drop_index(op.f('ix_amenity_bookings_society_id'), table_name='amenity_bookings')
    op.drop_index(op.f('ix_amenity_bookings_amenity_id'), table_name='amenity_bookings')
    op.drop_table('amenity_bookings')
    op.drop_index(op.f('ix_whatsapp_groups_society_id'), table_name='whatsapp_groups')
    op.drop_table('whatsapp_groups')
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_society_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_groups_society_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_amenities_society_id'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
